"""Fixed neural building blocks for the SAGA-PQ-CAN research prototype."""

from neural.can import CAN
from neural.compiled_lwe_dnn import (
    CompiledVerifierBoundary,
    CompiledToyLWEVerifier,
    FixedEqualityAggregator,
    FixedEqualityGate,
    FixedMatrixProjector,
    FixedModSubtractor,
    ProjectionTrace,
)
from neural.fixed_circuit import (
    TrainableStateFinding,
    assert_fixed_circuit,
    find_trainable_state,
)
from neural.fixed_toolchain import (
    FIXED_PROJECTOR_CORE_ID,
    MAX_EXACT_FLOAT_INTEGER,
    BinaryInputGuard,
    DenseFixedProjector,
    FixedBooleanAggregator,
    FixedEquality,
    FixedModReduce,
    FixedProjector,
    FixedProjectorCore,
    FixedRangeNormCheck,
    GadgetBoundary,
    ProjectorBoundary,
    ProjectorComplexity,
    ProjectorManifest,
    ProjectorTrace,
    RangeNormTrace,
    TinyNegacyclicProjector,
)
from neural.shamir_layers import (
    MASK,
    RECT13,
    STEP13,
    FixedLinear,
    FixedReLU,
    FixedSum,
)
from neural.shadow_queue import (
    A0ShadowEvidence,
    A0ShadowEvidenceOutbox,
    A0ShadowJob,
    A0ShadowQueueStats,
    A0ShadowStatus,
    A0ShadowSubmission,
    A0ShadowVerifier,
    BoundedA0ShadowQueue,
    InMemoryA0ShadowOutbox,
    MAX_A0_SHADOW_MATERIAL_BYTES,
)
from neural.verifier_wrapper import (
    BitLayout,
    CompoundBitVerifier,
    SignatureVerifierWrapper,
    bits_to_bytes,
    bytes_to_bits,
)

__all__ = [
    "BitLayout",
    "A0ShadowEvidence",
    "A0ShadowEvidenceOutbox",
    "A0ShadowJob",
    "A0ShadowQueueStats",
    "A0ShadowStatus",
    "A0ShadowSubmission",
    "A0ShadowVerifier",
    "BoundedA0ShadowQueue",
    "BinaryInputGuard",
    "CAN",
    "CompiledVerifierBoundary",
    "CompiledToyLWEVerifier",
    "CompoundBitVerifier",
    "DenseFixedProjector",
    "FIXED_PROJECTOR_CORE_ID",
    "FixedBooleanAggregator",
    "FixedEquality",
    "FixedEqualityAggregator",
    "FixedEqualityGate",
    "FixedLinear",
    "FixedMatrixProjector",
    "FixedModReduce",
    "FixedModSubtractor",
    "FixedProjector",
    "FixedProjectorCore",
    "FixedRangeNormCheck",
    "FixedReLU",
    "FixedSum",
    "InMemoryA0ShadowOutbox",
    "GadgetBoundary",
    "MAX_A0_SHADOW_MATERIAL_BYTES",
    "MAX_EXACT_FLOAT_INTEGER",
    "STEP13",
    "RECT13",
    "MASK",
    "ProjectionTrace",
    "ProjectorBoundary",
    "ProjectorComplexity",
    "ProjectorManifest",
    "ProjectorTrace",
    "RangeNormTrace",
    "TrainableStateFinding",
    "SignatureVerifierWrapper",
    "assert_fixed_circuit",
    "bits_to_bytes",
    "bytes_to_bits",
    "find_trainable_state",
    "TinyNegacyclicProjector",
]
